/**
 * ===================================================================
 * === CATÁLOGO DE PRODUCTOS - "EL RESOLVITO" (products.js) ===
 * ===================================================================
 * 
 * NOTA: La variable 'products' se declara aquí para uso global.
 */
var products = [
    // --- MERCADO ---
    { id: 1, name: "Aceite", price: 970, image: "https://i.postimg.cc/bvfLRwLH/aceite.jpg", description: "Botella de aceite vegetal.", specificDetails: "1 Litro", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 1.0 },
    { id: 2, name: "Arroz", price: 650, image: "https://i.postimg.cc/ZRR352mX/arroz.jpg", description: "Arroz brasileño, precio de oferta.", specificDetails: "Paquete de 1 kg", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 1.0 },
    { id: 3, name: "Spaghetti", price: 350, image: "https://i.postimg.cc/rpBWC2DW/spaguetis.png", description: "Pasta de trigo.", specificDetails: "Paquete de 500g", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 0.5 },
    { id: 4, name: "Picadillo", price: 380, image: "https://i.postimg.cc/pdhzFLLR/picadillo-de-pollo.png", description: "Carne molida de ave.", specificDetails: "Paquete de 500g", category: "Cárnicos", department: "mercado", status: "available", hasBoxOption: false, weight: 0.5 },
    { id: 5, name: "Salchichas", price: 400, image: "https://i.postimg.cc/R0mKFv73/salchichas-1-paquete.png", description: "Salchichas de ave.", specificDetails: "1 paquete (10 unid)", category: "Cárnicos", department: "mercado", status: "available", hasBoxOption: false, weight: 0.5 },
    { id: 6, name: "Cerveza Presidente", price: 220, image: "https://i.postimg.cc/sXBWqMwz/cerveza-predidente-precio-220.png", description: "Cerveza pilsener ligera.", specificDetails: "Lata de 355 ml", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: true, boxPrice: 5280, boxQuantity: 24, weight: 0.38 },
    { id: 7, name: "Malta Guajira", price: 250, image: "https://i.postimg.cc/HWv2h2BL/malta_guajira.jpg", description: "Bebida de malta refrescante.", specificDetails: "Botella de 355 ml", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: false, weight: 0.38 },
    { id: 8, name: "Leche Condensada", price: 520, image: "https://i.postimg.cc/fRbxMK43/leche-condensada.jpg", description: "Dulce y cremosa.", specificDetails: "Lata de 397g", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 0.45 },
    { id: 9, name: "Jabón Ridel", price: 160, image: "https://i.postimg.cc/rm2qNxty/jabon-de-ba-o.jpg", description: "Suave para la piel.", specificDetails: "Pastilla de 100g", category: "Aseo Personal", department: "mercado", status: "available", hasBoxOption: false, weight: 0.1 },
    { id: 10, name: "Refresco Instant.", price: 40, image: "https://i.postimg.cc/MTzsbBM1/refresco-1.png", description: "Sobre de refresco en polvo.", specificDetails: "Para 1.5 Litros", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: false, weight: 0.01 },
    { id: 11, name: "Hígado de Pollo", price: 850, image: "https://i.postimg.cc/Zn9vvrkb/higado.jpg", description: "Fresco y nutritivo.", specificDetails: "Paquete de 1 kg", category: "Cárnicos", department: "mercado", status: "available", hasBoxOption: false, weight: 1.0 },
    { id: 12, name: "Whisky Jolly", price: 400, image: "https://i.postimg.cc/mD2Ydz9M/whisky.png", description: "Bebida espirituosa.", specificDetails: "Botella de 200 ml", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: false, weight: 0.25 },
    { id: 13, name: "Frijol Negro", price: 880, image: "https://i.postimg.cc/rFt14B4k/frijol_negro.jpg", description: "Legumbre esencial.", specificDetails: "Paquete de 1 kg", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 1.0 },
    { id: 14, name: "Galletas SaltiBloks", price: 890, image: "https://i.postimg.cc/c4qpfNz7/Galletas-7-tacos.png", description: "Crujientes y saladas.", specificDetails: "1 paquete (7 tacos)", category: "Confituras", department: "mercado", status: "available", hasBoxOption: false, weight: 0.3 },
    { id: 15, name: "Detergente Brillante", price: 350, image: "https://i.postimg.cc/sXwcy9zw/detergente.jpg", description: "Limpieza profunda.", specificDetails: "Bolsa de 400g", category: "Aseo Personal", department: "mercado", status: "available", hasBoxOption: false, weight: 0.4 },
    { id: 16, name: "Cerveza Unlaguer", price: 250, image: "https://i.postimg.cc/HLv56w03/cerveza-ulaguer-precio-300.png", description: "Ligera y refrescante.", specificDetails: "Lata de 355 ml", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: true, boxPrice: 6000, boxQuantity: 24, weight: 0.38 },
    { id: 17, name: "Cerveza Cristal", price: 280, image: "https://i.postimg.cc/MZ5gbYw8/cristal.png", description: "Clásica cubana.", specificDetails: "Lata de 355 ml", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: true, boxPrice: 6720, boxQuantity: 24, weight: 0.38 },
    { id: 18, name: "Azúcar Blanca", price: 600, image: "https://i.postimg.cc/c40RbWXB/azucar_blanca.jpg", description: "Endulza tus momentos.", specificDetails: "Paquete de 1 kg", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 1.0 },
    { id: 19, name: "Papel Sanitario", price: 530, image: "https://i.postimg.cc/K8BD4yFK/papel_sanitario.jpg", description: "Suave y resistente.", specificDetails: "Paquete de 4 rollos", category: "Aseo Personal", department: "mercado", status: "available", hasBoxOption: false, weight: 0.5 },
    { id: 20, name: "Malta Morena", price: 210, image: "https://i.postimg.cc/7YCV82Wn/malta_morena.jpg", description: "Sabor intenso.", specificDetails: "Lata de 8 oz", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: false, weight: 0.25 },
    { id: 21, name: "Fritos", price: 200, image: "https://i.postimg.cc/GhqTCs0B/fritos.jpg", description: "Crujientes frituras.", specificDetails: "Paquete individual", category: "Confituras", department: "mercado", status: "available", hasBoxOption: false, weight: 0.05 },
    { id: 22, name: "Jabón Pemila", price: 160, image: "https://i.postimg.cc/X7qNdKr0/jabon_de_baño_pemila_.png", description: "Aroma fresco.", specificDetails: "Pastilla de 100g", category: "Aseo Personal", department: "mercado", status: "available", hasBoxOption: false, weight: 0.1 },
    { id: 23, name: "Pasta de Tomate", price: 120, image: "https://i.postimg.cc/k5CFbhXT/pasta_de_tomate.jpg", description: "Concentrado de tomate.", specificDetails: "Bolsa de 70g", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 0.07 },
    { id: 24, name: "Pelly de Queso", price: 500, image: "https://i.postimg.cc/Zq1yQkGV/pelly.jpg", description: "Sabor a queso.", specificDetails: "Paquete de 115g", category: "Confituras", department: "mercado", status: "available", hasBoxOption: false, weight: 0.12 },
    { id: 25, name: "Ron Capitán Cortez", price: 1500, image: "https://i.postimg.cc/xCzzpvCX/ron_capitan_cortez.jpg", description: "Ron brasileño.", specificDetails: "Botella de 965 ml", category: "Líquidos", department: "mercado", status: "available", hasBoxOption: false, weight: 1.5 },
    { id: 26, name: "Sorbeto Renata", price: 300, image: "https://i.postimg.cc/Wb6CbTSq/sorbeto-renata.jpg", description: "Dulce sabor a frutas.", specificDetails: "Paquete de 115g", category: "Confituras", department: "mercado", status: "available", hasBoxOption: false, weight: 0.15 },
    { id: 29, name: "Mermelada Fresa", price: 600, image: "https://i.postimg.cc/Kvd5ZYXS/mermelada.jpg", description: "Mermelada de fresa.", specificDetails: "Frasco de 200g", category: "Mercado", department: "mercado", status: "available", hasBoxOption: false, weight: 0.2 },
    
    // --- ROPA y CALZADO (Nuevos) ---
    { id: 30, name: "Chaqueta Deportiva Negra", price: 4500, image: "https://i.postimg.cc/MKC9DP0n/1764656017651.png", description: "Chaqueta casual/deportiva con capucha.", specificDetails: "Tallas S a XL", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 0.5 },
    { id: 31, name: "Pantalón Jogger Gris", price: 3800, image: "https://i.postimg.cc/9XN84FrG/1764655530658.jpg", description: "Pantalón de tela suave y diseño moderno.", specificDetails: "Tallas 30 a 38", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 0.4 },
    { id: 32, name: "Sudadera Casual Roja", price: 4200, image: "https://i.postimg.cc/gkCgDSyr/1764655401339.png", description: "Sudadera cómoda y con estilo.", specificDetails: "Tallas M a XXL", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 0.6 },
    { id: 33, name: "Tenis Deportivos Urbanos", price: 5500, image: "https://i.postimg.cc/xTw6RxGb/1764655468915.png", description: "Calzado deportivo de alta calidad y diseño moderno.", specificDetails: "Tallas 38 a 44", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 0.8 },
    { id: 34, name: "Gorra Negra Clásica", price: 800, image: "https://i.postimg.cc/W4jXRdHL/1765241753280.png", description: "Gorra ajustable, ideal para el día a día.", specificDetails: "Talla única", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 0.1 },
    { id: 35, name: "Mochila Táctica", price: 2500, image: "https://i.postimg.cc/jjKZVDFt/1765241768249.png", description: "Mochila resistente con múltiples compartimentos.", specificDetails: "Capacidad 25L", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 0.7 },
    { id: 36, name: "Guantes de Ciclismo", price: 950, image: "https://i.postimg.cc/ZqcjJJGZ/1765241794196.png", description: "Guantes acolchados con agarre antideslizante.", specificDetails: "Tallas M y L", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 0.1 },
    { id: 41, name: "Juego de Abrigo Lujo", price: 8500, image: "https://i.postimg.cc/3r618ScG/juego_de_abrigo_8500_pesos.png", description: "Conjunto de abrigo de alta gama, ideal para clima frío.", specificDetails: "Tallas M y L", category: "Ropa y Calzado", department: "ropa", status: "available", hasBoxOption: false, weight: 1.2 },

    // --- ELECTRODOMÉSTICOS (Nuevos) ---
    { id: 37, name: "Botella de Agua Térmica", price: 1200, image: "https://i.postimg.cc/HL23TTq8/1765241803048.png", description: "Mantiene la temperatura por horas.", specificDetails: "Acero inoxidable, 500 ml", category: "Hogar", department: "electro", status: "available", hasBoxOption: false, weight: 0.3 },
    { id: 38, name: "Auriculares Inalámbricos", price: 3100, image: "https://i.postimg.cc/W4nSssBg/1765241852697.png", description: "Sonido de alta fidelidad con estuche de carga.", specificDetails: "Bluetooth 5.0", category: "Tecnología", department: "electro", status: "available", hasBoxOption: false, weight: 0.2 },
    { id: 39, name: "Cargador Rápido USB-C", price: 1800, image: "https://i.postimg.cc/0QXfJc2r/1765242105732.png", description: "Cargador de pared con tecnología de carga rápida.", specificDetails: "20W", category: "Tecnología", department: "electro", status: "available", hasBoxOption: false, weight: 0.1 },
    { id: 40, name: "Smartwatch Deportivo", price: 6800, image: "https://i.postimg.cc/4yK1vVmH/1765242197065.png", description: "Reloj inteligente con monitor de ritmo cardíaco y GPS.", specificDetails: "Pantalla AMOLED", category: "Tecnología", department: "electro", status: "available", hasBoxOption: false, weight: 0.15 }
];